### ISSUE TITLE
[Bug]: Execution of integration test sometimes hang on the CI

### ISSUE THREAD

**Issue by kargolek** [kargolek/crypto-portfolio-microservices#1]
### Severity

Minor

### Bug Category

Freeze/Hangs

### Frequency

Occasional (5/10)

### Summary

Sometimes when push branch to the repo CI test execution hangs and stucks in the below tests
[INFO] +--pl.kargolek.cryptopriceservice.service.PriceServiceIntegrationTest - 19.696s
[INFO] |  +-- [OK] whenUpdatePricesByNotExistPrice_thenThrowPriceNotFoundExc - 0.4s
[INFO] |  +-- [OK] whenUpdatePricesByEmptyList_thenReturnEmptyEntitiesList - 0.028s
[INFO] |  '-- [OK] whenUpdatePrice_thenPriceShouldUpdatedSuccessful - 0.085s
[INFO] +--pl.kargolek.cryptopriceservice.service.PriceUpdateServiceIntegrationTest - 2.562s

The issue occurs occasionaly and any error isn't thrown. It didn't happen on the local machine even once. Need to find root cause.

### Reproduction steps

1.  Push changes to the repo
2.  Open Actions
3.  Click on the build_test
4. Observe ongoing build project

### Actual Results

1. Tests are stucked during execution, without thrown any error.

### Expected Results

1.  Test should be executed to the end
2.  If error occurrs, it should be thrown.

### Relevant log output

```shell
[INFO] +--pl.kargolek.cryptopriceservice.service.PriceServiceIntegrationTest - 19.696s
[INFO] |  +-- [OK] whenUpdatePricesByNotExistPrice_thenThrowPriceNotFoundExc - 0.4s
[INFO] |  +-- [OK] whenUpdatePricesByEmptyList_thenReturnEmptyEntitiesList - 0.028s
[INFO] |  '-- [OK] whenUpdatePrice_thenPriceShouldUpdatedSuccessful - 0.085s
[INFO] +--pl.kargolek.cryptopriceservice.service.PriceUpdateServiceIntegrationTest - 2.562s
```

**Comment by kargolek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[CPA-29] Execution of integration test sometimes hang on the CI](https://trello.com/c/hn6uRLRo/29-cpa-29-execution-of-integration-test-sometimes-hang-on-the-ci)

**Comment by kargolek** [comment]
New logs provided when stuck occurrs:

```shell
[INFO] Running pl.kargolek.cryptopriceservice.service.PriceUpdateServiceIntegrationTest
03:11:50.500 [main] INFO  org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Neither @ContextConfiguration nor @ContextHierarchy found for test class [pl.kargolek.cryptopriceservice.service.PriceUpdateServiceIntegrationTest], using SpringBootContextLoader
03:11:50.501 [main] INFO  org.springframework.test.context.support.AbstractContextLoader - Could not detect default resource locations for test class [pl.kargolek.cryptopriceservice.service.PriceUpdateServiceIntegrationTest]: no resource found for suffixes {-context.xml, Context.groovy}.
03:11:50.504 [main] INFO  org.springframework.test.context.support.AnnotationConfigContextLoaderUtils - Could not detect default configuration classes for test class [pl.kargolek.cryptopriceservice.service.PriceUpdateServiceIntegrationTest]: PriceUpdateServiceIntegrationTest does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
03:11:50.509 [main] INFO  org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Found @SpringBootConfiguration pl.kargolek.cryptopriceservice.CryptoPriceServiceApplication for test class pl.kargolek.cryptopriceservice.service.PriceUpdateServiceIntegrationTest
03:11:50.512 [main] INFO  org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.event.A...
03:11:50.514 [main] INFO  org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@3[244](https://github.com/kargolek/crypto-portfolio-microservices/actions/runs/3992654557/jobs/6848712779#step:6:245)1ed4, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@3fc2197d, org.springframework.test.context.event.ApplicationEventsTestExecutionListener@5a429813, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@348b26e0, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@26ab3c1b, org.springframework.test.context.support.DirtiesContextTestExecutionListener@98dc042, org.springframework.test.context.transaction.TransactionalTestExecutionListener@47c14360, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@2a90c15e, org.springframework.test.context.event.EventPublishingTestExecutionListener@55a46bf3, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@324c3ed5, org.springframewo...
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.8)
03:11:50.571 [main] INFO  pl.kargolek.cryptopriceservice.service.PriceUpdateServiceIntegrationTest - Starting PriceUpdateServiceIntegrationTest using Java 17.0.6 on fv-az166-272 with PID 2626 (started by runner in /home/runner/work/crypto-portfolio-microservices/crypto-portfolio-microservices/crypto-price-service)
03:11:50.571 [main] INFO  pl.kargolek.cryptopriceservice.service.PriceUpdateServiceIntegrationTest - No active profile set, falling back to 1 default profile: "default"
03:11:50.759 [main] INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
03:11:50.769 [main] INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate - Finished Spring Data repository scanning in 9 ms. Found 2 JPA repository interfaces.
03:11:50.959 [main] INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer - Tomcat initialized with port(s): 0 (http)
03:11:50.960 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-auto-2"]
03:11:50.960 [main] INFO  org.apache.catalina.core.StandardService - Starting service [Tomcat]
03:11:50.960 [main] INFO  org.apache.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.71]
03:11:50.986 [main] INFO  org.apache.catalina.core.ContainerBase.[Tomcat-1].[localhost].[/] - Initializing Spring embedded WebApplicationContext
03:11:50.987 [main] INFO  org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 414 ms
03:11:51.091 [main] INFO  org.hibernate.jpa.internal.util.LogHelper - HHH000204: Processing PersistenceUnitInfo [name: default]
03:11:51.098 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
03:11:51.116 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Start completed.
03:11:51.116 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.MySQL57Dialect
03:11:51.328 [main] INFO  org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
03:11:51.328 [main] INFO  org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default'
03:11:51.506 [main] WARN  org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration - spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
03:11:51.667 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-auto-2"]
03:11:51.675 [main] INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer - Tomcat started on port(s): 34677 (http) with context path ''
03:11:51.679 [main] INFO  pl.kargolek.cryptopriceservice.service.PriceUpdateServiceIntegrationTest - Started PriceUpdateServiceIntegrationTest in 1.137 seconds (JVM running for 18.148)
03:11:51.688 [scheduling-1] INFO  pl.kargolek.cryptopriceservice.service.ScheduledPriceUpdateTask - Running scheduled update price job
03:11:51.688 [scheduling-1] INFO  pl.kargolek.cryptopriceservice.service.CryptocurrencyService - Finding all cryptocurrencies
03:11:51.704 [main] INFO  pl.kargolek.cryptopriceservice.service.CryptocurrencyService - Finding all cryptocurrencies
03:11:51.714 [scheduling-1] INFO  pl.kargolek.cryptopriceservice.service.impl.MarketApiClientImpl - Calling get request for path:/v2/cryptocurrency/quotes/latest, query:id=1
03:11:51.715 [main] INFO  pl.kargolek.cryptopriceservice.service.impl.MarketApiClientImpl - Calling get request for path:/v2/cryptocurrency/quotes/latest, query:id=1,1027
03:11:52.045 [main] INFO  pl.kargolek.cryptopriceservice.service.PriceService - Updating price id:1, new price: [250](https://github.com/kargolek/crypto-portfolio-microservices/actions/runs/3992654557/jobs/6848712779#step:6:251)00.12345
03:11:52.045 [main] INFO  pl.kargolek.cryptopriceservice.service.PriceService - Updating price id:2, new price: 1800.500000000000
03:11:52.107 [main] INFO  pl.kargolek.cryptopriceservice.service.CryptocurrencyService - Finding all cryptocurrencies
03:11:52.112 [scheduling-1] ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
pl.kargolek.cryptopriceservice.exception.PriceNotFoundException: Unable to find price entity for a new price
	at pl.kargolek.cryptopriceservice.service.PriceService.updatePrices(PriceService.java:29)
	at pl.kargolek.cryptopriceservice.service.PriceUpdateService.updateCryptocurrencyPrices(PriceUpdateService.java:57)
	at pl.kargolek.cryptopriceservice.service.ScheduledPriceUpdateTask.scheduledUpdatePriceJob(ScheduledPriceUpdateTask.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
03:11:52.118 [main] INFO  pl.kargolek.cryptopriceservice.service.impl.MarketApiClientImpl - Calling get request for path:/v2/cryptocurrency/quotes/latest, query:id=1,1027
03:21:50.256 [scheduling-1] INFO  pl.kargolek.cryptopriceservice.service.ScheduledPriceUpdateTask - Running scheduled update price job
03:21:50.257 [scheduling-1] INFO  pl.kargolek.cryptopriceservice.service.CryptocurrencyService - Finding all cryptocurrencies
03:21:50.265 [scheduling-1] INFO  pl.kargolek.cryptopriceservice.service.impl.MarketApiClientImpl - Calling get request for path:/v2/cryptocurrency/quotes/latest, query:id=1,1027
03:21:50.542 [scheduling-1] ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
pl.kargolek.cryptopriceservice.exception.MarketApiClientException: Status code: 401, clientMessage: Error during calling get request, serverMessage: API key missing.
	at pl.kargolek.cryptopriceservice.service.impl.MarketApiClientImpl.lambda$getRequest$1(MarketApiClientImpl.java:43)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ 401 from GET https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest [DefaultWebClient]
Original Stack Trace:
		at pl.kargolek.cryptopriceservice.service.impl.MarketApiClientImpl.lambda$getRequest$1(MarketApiClientImpl.java:43)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299)
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
		at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
		at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
		at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:424)
		at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:478)
		at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:712)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:[251](https://github.com/kargolek/crypto-portfolio-microservices/actions/runs/3992654557/jobs/6848712779#step:6:252))
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
		at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
		at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1[285](https://github.com/kargolek/crypto-portfolio-microservices/actions/runs/3992654557/jobs/6848712779#step:6:286))
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:[290](https://github.com/kargolek/crypto-portfolio-microservices/actions/runs/3992654557/jobs/6848712779#step:6:291))
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:123)
		at reactor.core.publisher.Mono.blockOptional(Mono.java:1787)
		at pl.kargolek.cryptopriceservice.service.impl.MarketApiClientImpl.getRequest(MarketApiClientImpl.java:46)
		at pl.kargolek.cryptopriceservice.service.MarketApiClientService.getLatestPriceByIds(MarketApiClientService.java:45)
		at pl.kargolek.cryptopriceservice.service.PriceUpdateService.updateCryptocurrencyPrices(PriceUpdateService.java:46)
		at pl.kargolek.cryptopriceservice.service.ScheduledPriceUpdateTask.scheduledUpdatePriceJob(ScheduledPriceUpdateTask.java:22)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
		at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)
03:21:52.112 [scheduling-1] INFO  pl.kargolek.cryptopriceservice.service.ScheduledPriceUpdateTask - Running scheduled update price job
03:21:52.112 [scheduling-1] INFO  pl.kargolek.cryptopriceservice.service.CryptocurrencyService - Finding all cryptocurrencies
03:21:52.121 [scheduling-1] INFO  pl.kargolek.cryptopriceservice.service.impl.MarketApiClientImpl - Calling get request for path:/v2/cryptocurrency/quotes/latest, query:id=1,1027
03:31:50.544 [scheduling-1] INFO  pl.kargolek.cryptopriceservice.service.ScheduledPriceUpdateTask - Running scheduled update price job
03:31:50.544 [scheduling-1] INFO  pl.kargolek.cryptopriceservice.service.CryptocurrencyService - Finding all cryptocurrencies
03:31:50.552 [scheduling-1] INFO  pl.kargolek.cryptopriceservice.service.impl.MarketApiClientImpl - Calling get request for path:/v2/cryptocurrency/quotes/latest, query:id=1,1027
03:31:50.888 [scheduling-1] ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
pl.kargolek.cryptopriceservice.exception.MarketApiClientException: Status code: 401, clientMessage: Error during calling get request, serverMessage: API key missing.
	at pl.kargolek.cryptopriceservice.service.impl.MarketApiClientImpl.lambda$getRequest$1(MarketApiClientImpl.java:43)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ 401 from GET https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest [DefaultWebClient]
Original Stack Trace:
		at pl.kargolek.cryptopriceservice.service.impl.MarketApiClientImpl.lambda$getRequest$1(MarketApiClientImpl.java:43)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:[299](https://github.com/kargolek/crypto-portfolio-microservices/actions/runs/3992654557/jobs/6848712779#step:6:300))
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839)
		at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160)
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
		at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
		at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:424)
		at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:478)
		at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:712)
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
		at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
		at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:123)
		at reactor.core.publisher.Mono.blockOptional(Mono.java:1787)
		at pl.kargolek.cryptopriceservice.service.impl.MarketApiClientImpl.getRequest(MarketApiClientImpl.java:46)
		at pl.kargolek.cryptopriceservice.service.MarketApiClientService.getLatestPriceByIds(MarketApiClientService.java:45)
		at pl.kargolek.cryptopriceservice.service.PriceUpdateService.updateCryptocurrencyPrices(PriceUpdateService.java:46)
		at pl.kargolek.cryptopriceservice.service.ScheduledPriceUpdateTask.scheduledUpdatePriceJob(ScheduledPriceUpdateTask.java:22)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
		at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:[305](https://github.com/kargolek/crypto-portfolio-microservices/actions/runs/3992654557/jobs/6848712779#step:6:306))
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by kargolek** [comment]
Scheduled update price was invoked during test and it was root cause on hang issue.
Resolve:
1. The parameterized value for initial delay for the shceduled job price updates was added as test profile.
2. Add active profile -> test to PriceUpdateServiceIntegrationTest class

**Comment by kargolek** [comment]
Testing changes in https://github.com/kargolek/crypto-portfolio-microservices/actions/runs/3994791017 by re-run after complete
